### ISSUE TITLE
cookies with custom path not showing.

### ISSUE THREAD

**Issue by FaizanYounasTanooli** [andreizanik/cookies-next#31]
I am not finding anything about this anywhere so opened issue

I set cookie with name orgID and  path '/org'
I am trying to post data from path /org/add/user 
the API I call from /org/add/user is  post request to  /api/add/org/department

and in the department.js I am trying to get that cookie its not there. only cookies with path '/' are showing.
please tell me if I am doing something wrong.

**Comment by andreizanik** [comment]
I think the problem is that url of the page and called api url are different.

You set cookie with name orgID and path '/org'. And I think you can get them on the page "/org/add/user". For example in some component or in the getServerSideProps function. 
But your api has a different url, so cookie "orgID" isn't available there.

Try setting cookies with path '/api' or '/api/add/org', then they should be available in your api handler "department.js"


I recommend reading about this attribute here https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent

**Comment by FaizanYounasTanooli** [comment]
Ok thanks let me check.
But this means
Client side will not show any cookies in use.

**Comment by andreizanik** [comment]
Of course, due to different URLs.
But this is not a package problem, but a standard. 
https://www.rfc-editor.org/rfc/rfc6265#section-5.1.4

**Comment by andreizanik** [comment]
@FaizanYounasTanooli did you solve your problem? Do you have any more questions?

**Comment by andreizanik** [comment]
I think this issue can be closed

**Comment by FaizanYounasTanooli** [comment]
> @FaizanYounasTanooli did you solve your problem? Do you have any more questions?

i just used the root address for all cookies
but that's not look ok
